// ============================================================
// ALEXANDER'S QUEST - LIVING LEGACY CAPSULE 🏛️
// "Светска Тестамент-Капсула на Александар"
// World's First: Player-Generated Wisdom Wall + Knowledge Passport + Shareable Wisdom Sparks
// Backend-FREE. Client-only. Privacy-first.
// ============================================================

const Legacy = {
  STORAGE_KEY: 'alexander_legacy_v1',
  WISDOM_WALL_KEY: 'alexander_wisdom_wall_v1',
  PASSPORT_KEY: 'alexander_passport_v1',

  // === LOAD/SAVE ===
  load() {
    try {
      return JSON.parse(localStorage.getItem(this.STORAGE_KEY) || '{}');
    } catch(e) { return {}; }
  },
  save(data) {
    try { localStorage.setItem(this.STORAGE_KEY, JSON.stringify(data)); } catch(e) {}
  },

  // === WISDOM WALL — community quotes generated by players ===
  getWisdomWall() {
    try {
      const local = JSON.parse(localStorage.getItem(this.WISDOM_WALL_KEY) || '[]');
      // Seed with 12 starter quotes from legendary thinkers (rotated demo)
      if (local.length === 0) {
        return [
          { author: 'Аристотел', quote: 'Знаењето на малкумина е оружје — знаењето на многумина е светлина.', date: '356 п.н.е.', kind: 'мудрец' },
          { author: 'Александар', quote: 'Не се плашам од армија лавови водена од овца, туку од армија овци водена од лав.', date: '331 п.н.е.', kind: 'крал' },
          { author: 'Букефал', quote: 'Сенката беше моја, не ме плашеше повеќе.', date: '344 п.н.е.', kind: 'коњ' },
          { author: 'Хефестион', quote: 'Заедно сме непобедливи — секој сам, обичен човек.', date: '330 п.н.е.', kind: 'пријател' },
          { author: 'Птоломеј', quote: 'Изгубениот свиток вреди повеќе од освоен град.', date: '305 п.н.е.', kind: 'учен' },
          { author: 'Диоген', quote: 'Тргни се од моето сонце — побарав знаење, не моќ.', date: '336 п.н.е.', kind: 'филозоф' },
        ].concat(local);
      }
      return local;
    } catch(e) { return []; }
  },

  addToWisdomWall(quote, author) {
    if (!quote || quote.trim().length < 5) return false;
    if (quote.length > 200) quote = quote.substring(0, 200);
    const wall = JSON.parse(localStorage.getItem(this.WISDOM_WALL_KEY) || '[]');
    const entry = {
      author: author || state.playerName || 'Анонимен патник',
      quote: quote.trim(),
      date: new Date().toLocaleDateString('mk-MK'),
      kind: 'играч',
      timestamp: Date.now()
    };
    wall.unshift(entry);
    // Keep newest 50 player quotes
    if (wall.length > 50) wall.pop();
    localStorage.setItem(this.WISDOM_WALL_KEY, JSON.stringify(wall));
    return true;
  },

  renderWisdomWall() {
    const container = document.getElementById('wisdom-wall-list');
    if (!container) return;
    const wall = this.getWisdomWall();
    container.innerHTML = wall.map((entry, i) => {
      const isPlayer = entry.kind === 'играч';
      const accentColor = isPlayer ? 'border-blue-500/40 bg-blue-500/5' : 'border-yellow-500/30 bg-yellow-500/5';
      const iconMap = { 'мудрец':'📚','крал':'👑','коњ':'🐴','пријател':'⚔️','учен':'🏛️','филозоф':'🕯️','играч':'✨' };
      const icon = iconMap[entry.kind] || '📜';
      return `
        <div class="p-4 rounded-2xl border-2 ${accentColor} transition-all hover:scale-[1.02]" style="animation: slideIn 0.5s ease-out ${i*0.05}s both">
          <div class="flex items-start gap-3">
            <span class="text-3xl">${icon}</span>
            <div class="flex-1">
              <p class="text-[#FFF8E7]/90 italic mb-2 leading-relaxed">"${entry.quote}"</p>
              <div class="flex items-center justify-between text-xs">
                <span class="text-yellow-400 font-bold">— ${entry.author}</span>
                <span class="text-[#FFF8E7]/40">${entry.date}</span>
              </div>
            </div>
          </div>
        </div>`;
    }).join('');

    document.getElementById('wisdom-wall-count').textContent = wall.length;
  },

  submitWisdom() {
    const input = document.getElementById('wisdom-input');
    if (!input || !input.value.trim()) {
      alert('Напиши своја мудрост прво!');
      return;
    }
    const success = this.addToWisdomWall(input.value, state.playerName);
    if (success) {
      // 👁️ Magic Tracking
      if(window.MagicTracking) MagicTracking.trackEvent('wisdom_submitted', { length: input.value.length, player: state.playerName });
      // Coins reward
      state.totalCoins += 25;
      saveState(state);
      document.getElementById('hud-coins')?.replaceChildren(document.createTextNode(state.totalCoins));
      // Confetti
      if (typeof confetti === 'function') {
        confetti({ particleCount: 50, spread: 60, origin: {y:0.7}, colors:['#FFD700','#4A90E2','#FFA500'] });
      }
      input.value = '';
      this.renderWisdomWall();
      // Toast
      this.showToast('✨ +25 монети! Твојата мудрост е дел од светот!');
    }
  },

  // === KNOWLEDGE PASSPORT — visual SVG passport with 37 stamps ===
  generatePassportSVG() {
    const completedLevels = state.completedLevels || [];
    const stars = state.levelStars || {};
    const name = state.playerName || 'Патник';
    const totalStars = Object.values(stars).reduce((s,v)=>s+v, 0);
    const dateStr = new Date().toLocaleDateString('mk-MK');
    const passportId = this.getPassportId();

    // Calculate hex color for player (deterministic from name)
    const hash = name.split('').reduce((h,c)=>((h<<5)-h+c.charCodeAt(0))|0, 0);
    const hue = Math.abs(hash) % 360;
    const playerColor = `hsl(${hue}, 70%, 55%)`;

    // 37 stamps grid (6x7 = 42 slots, 37 used)
    let stampsHTML = '';
    for(let i=1; i<=37; i++){
      const col = (i-1) % 6;
      const row = Math.floor((i-1) / 6);
      const cx = 60 + col * 65;
      const cy = 280 + row * 55;
      const completed = completedLevels.includes(i);
      const starCount = stars[i] || 0;
      const fill = completed ? '#FFD700' : '#2a2030';
      const stroke = completed ? '#FFA500' : '#4a3a5a';
      const opacity = completed ? '1' : '0.4';
      stampsHTML += `
        <g opacity="${opacity}">
          <circle cx="${cx}" cy="${cy}" r="20" fill="${fill}" stroke="${stroke}" stroke-width="2"/>
          <text x="${cx}" y="${cy+1}" text-anchor="middle" dominant-baseline="middle" font-family="Georgia, serif" font-size="13" font-weight="bold" fill="${completed?'#0F0C18':'#888'}">${i}</text>
          ${completed && starCount>0 ? `<text x="${cx}" y="${cy+30}" text-anchor="middle" font-size="9" fill="#FFD700">${'★'.repeat(starCount)}</text>` : ''}
        </g>`;
    }

    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 720" width="100%" style="max-width:480px;background:linear-gradient(135deg,#1A1525,#0F0C18);border-radius:20px">
      <!-- Header band -->
      <rect x="0" y="0" width="480" height="100" fill="${playerColor}" opacity="0.25"/>
      <text x="240" y="40" text-anchor="middle" font-family="Georgia, serif" font-size="22" font-weight="bold" fill="#FFD700">СВЕТСКИ ПАСОШ НА ЗНАЕЊЕТО</text>
      <text x="240" y="62" text-anchor="middle" font-family="Georgia, serif" font-size="13" fill="#FFF8E7" opacity="0.7">МИСИЈА НА АЛЕКСАНДАР · ПАТОТ НА СВЕТЛИНАТА</text>
      <text x="240" y="82" text-anchor="middle" font-family="monospace" font-size="10" fill="#FFD700" opacity="0.6">ID: ${passportId}</text>

      <!-- Crown -->
      <text x="240" y="140" text-anchor="middle" font-size="44">👑</text>

      <!-- Player info -->
      <text x="240" y="180" text-anchor="middle" font-family="Georgia, serif" font-size="26" font-weight="bold" fill="#FFD700">${this.escapeXml(name)}</text>
      <text x="240" y="205" text-anchor="middle" font-family="sans-serif" font-size="13" fill="#FFF8E7" opacity="0.6">Издаден: ${dateStr}</text>

      <!-- Stats line -->
      <rect x="40" y="225" width="400" height="36" fill="rgba(255,215,0,0.08)" stroke="rgba(255,215,0,0.3)" stroke-width="1" rx="8"/>
      <text x="100" y="248" text-anchor="middle" font-size="11" fill="#FFF8E7" opacity="0.6">НИВОА</text>
      <text x="100" y="257" text-anchor="middle" font-family="Georgia, serif" font-size="15" font-weight="bold" fill="#FFD700">${completedLevels.length}/37</text>
      <text x="240" y="248" text-anchor="middle" font-size="11" fill="#FFF8E7" opacity="0.6">ЅВЕЗДИ</text>
      <text x="240" y="257" text-anchor="middle" font-family="Georgia, serif" font-size="15" font-weight="bold" fill="#FFD700">${totalStars}/111</text>
      <text x="380" y="248" text-anchor="middle" font-size="11" fill="#FFF8E7" opacity="0.6">МОНЕТИ</text>
      <text x="380" y="257" text-anchor="middle" font-family="Georgia, serif" font-size="15" font-weight="bold" fill="#FFD700">${state.totalCoins||0}</text>

      <!-- 37 stamps grid -->
      ${stampsHTML}

      <!-- Footer -->
      <line x1="40" y1="610" x2="440" y2="610" stroke="rgba(255,215,0,0.3)" stroke-width="1"/>
      <text x="240" y="635" text-anchor="middle" font-family="Georgia, serif" font-style="italic" font-size="13" fill="#FFF8E7" opacity="0.7">"Светот е книга, а оние кои патуваат читаат повеќе страници."</text>
      <text x="240" y="655" text-anchor="middle" font-family="Georgia, serif" font-size="11" fill="#FFD700" opacity="0.5">— ALEXANDER'S QUEST · WORLD PROTOCOL ACADEMY</text>

      <!-- QR-like badge (decorative) -->
      ${this.renderQRBadge(420, 670, passportId)}

      <!-- Decorative corner crowns -->
      <text x="25" y="30" font-size="18" opacity="0.4">⚜</text>
      <text x="455" y="30" text-anchor="end" font-size="18" opacity="0.4">⚜</text>
      <text x="25" y="710" font-size="18" opacity="0.4">⚜</text>
      <text x="455" y="710" text-anchor="end" font-size="18" opacity="0.4">⚜</text>
    </svg>`;
  },

  getPassportId() {
    let id = localStorage.getItem(this.PASSPORT_KEY);
    if (!id) {
      // Deterministic ID from name + timestamp
      const hash = Date.now().toString(36).toUpperCase();
      id = 'AQ-' + hash.substring(0,4) + '-' + hash.substring(4,8);
      localStorage.setItem(this.PASSPORT_KEY, id);
    }
    return id;
  },

  renderQRBadge(x, y, id) {
    // Stylized "QR-like" decorative badge (not a real QR — pure visual)
    let cells = '';
    const seed = id.split('').reduce((h,c)=>((h<<5)-h+c.charCodeAt(0))|0, 0);
    for(let i=0;i<5;i++){
      for(let j=0;j<5;j++){
        if (((seed >> (i*5+j)) & 1) || (i===0&&j===0) || (i===4&&j===4) || (i===0&&j===4)) {
          cells += `<rect x="${x-25+j*5}" y="${y-25+i*5}" width="4" height="4" fill="#FFD700" opacity="0.7"/>`;
        }
      }
    }
    return cells;
  },

  escapeXml(s) {
    return String(s).replace(/[<>&"']/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
  },

  showPassport() {
    const screen = document.getElementById('screen-passport');
    const isAlreadyActive = screen && screen.classList.contains('active');
    if (!isAlreadyActive) showScreen('passport');
    const svgHost = document.getElementById('passport-svg-host');
    if (svgHost) svgHost.innerHTML = this.generatePassportSVG();
  },

  downloadPassport() {
    // 👁️ Magic Tracking
    if(window.MagicTracking) MagicTracking.trackEvent('passport_downloaded', { player: state.playerName, levels: state.completedLevels.length });
    const svg = this.generatePassportSVG();
    const blob = new Blob([svg], {type:'image/svg+xml'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aleksandar_pasos_${state.playerName||'patnik'}.svg`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    this.showToast('📜 Пасошот е симнат!');
  },

  // === WISDOM SPARK — shareable quote card when collecting a scroll ===
  showWisdomSpark(fact) {
    if (!fact) return;
    const modal = document.getElementById('modal-wisdom-spark');
    if (!modal) return;

    // Generate gradient color from fact id
    const hue1 = (fact.id * 37) % 360;
    const hue2 = (fact.id * 73 + 60) % 360;
    const sparkSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 400" style="width:100%;border-radius:16px">
      <defs>
        <linearGradient id="bg-${fact.id}" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="hsl(${hue1},65%,30%)"/>
          <stop offset="100%" stop-color="hsl(${hue2},65%,15%)"/>
        </linearGradient>
      </defs>
      <rect width="600" height="400" fill="url(#bg-${fact.id})"/>
      <circle cx="100" cy="100" r="80" fill="#FFD700" opacity="0.1"/>
      <circle cx="520" cy="320" r="100" fill="#4A90E2" opacity="0.1"/>
      <text x="300" y="80" text-anchor="middle" font-size="36" fill="#FFD700">📜</text>
      <text x="300" y="130" text-anchor="middle" font-family="Georgia, serif" font-size="22" font-weight="bold" fill="#FFD700">${this.escapeXml(fact.title)}</text>
      <foreignObject x="50" y="160" width="500" height="160">
        <div xmlns="http://www.w3.org/1999/xhtml" style="color:white;font-family:Georgia,serif;font-size:18px;line-height:1.5;text-align:center;font-style:italic;padding:0 20px">
          "${this.escapeXml(fact.text)}"
        </div>
      </foreignObject>
      <text x="300" y="360" text-anchor="middle" font-family="sans-serif" font-size="13" fill="#FFD700" opacity="0.7">МИСИЈА НА АЛЕКСАНДАР · ${fact.id}/37</text>
      <text x="300" y="380" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#FFF8E7" opacity="0.5">aleksandar.makedonija</text>
    </svg>`;

    document.getElementById('spark-svg-host').innerHTML = sparkSvg;
    document.getElementById('spark-fact-id').textContent = fact.id;
    document.getElementById('spark-title').textContent = fact.title;
    modal.classList.remove('hidden');
    modal.dataset.factId = fact.id;
  },

  shareWisdomSpark() {
    const modal = document.getElementById('modal-wisdom-spark');
    const factId = parseInt(modal.dataset.factId);
    const fact = FACTS.find(f => f.id === factId);
    if (!fact) return;

    // 👁️ Magic Tracking
    if(window.MagicTracking) MagicTracking.trackEvent('wisdom_spark_shared', { factId, title: fact.title });

    const shareText = `📜 "${fact.title}"\n\n${fact.text}\n\n— Мисија на Александар, Ниво ${fact.id}/37`;

    // Try Web Share API first (mobile-friendly)
    if (navigator.share) {
      navigator.share({
        title: 'Мудрост на Александар',
        text: shareText,
        url: window.location.href
      }).catch(()=>{
        this.copyToClipboard(shareText);
      });
    } else {
      this.copyToClipboard(shareText);
    }
  },

  downloadWisdomSpark() {
    const svg = document.getElementById('spark-svg-host').querySelector('svg');
    if (!svg) return;
    const svgStr = new XMLSerializer().serializeToString(svg);
    const blob = new Blob([svgStr], {type:'image/svg+xml'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mudrost_${document.getElementById('spark-fact-id').textContent}.svg`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    this.showToast('🎁 Мудроста е симната!');
  },

  copyToClipboard(text) {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(text).then(()=>{
        this.showToast('📋 Копирано во клипборд!');
      });
    } else {
      // Fallback
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      try { document.execCommand('copy'); this.showToast('📋 Копирано!'); } catch(e){}
      document.body.removeChild(ta);
    }
  },

  // === TOAST notification ===
  showToast(message) {
    let toast = document.getElementById('legacy-toast');
    if (!toast) {
      toast = document.createElement('div');
      toast.id = 'legacy-toast';
      toast.style.cssText = 'position:fixed;bottom:30px;left:50%;transform:translateX(-50%) translateY(100px);background:linear-gradient(135deg,#FFD700,#FFA500);color:#0F0C18;padding:14px 24px;border-radius:9999px;font-weight:700;box-shadow:0 10px 40px rgba(255,215,0,0.4);z-index:10000;transition:transform 0.4s cubic-bezier(0.34,1.56,0.64,1);font-family:Inter,sans-serif';
      document.body.appendChild(toast);
    }
    toast.textContent = message;
    toast.style.transform = 'translateX(-50%) translateY(0)';
    clearTimeout(this._toastTimer);
    this._toastTimer = setTimeout(()=>{
      toast.style.transform = 'translateX(-50%) translateY(100px)';
    }, 2500);
  },

  // === LEGACY CAPSULE — final epic moment when finishing level 37 ===
  showCapsule() {
    const screen = document.getElementById('screen-capsule');
    const isAlreadyActive = screen && screen.classList.contains('active');
    if (!isAlreadyActive) showScreen('capsule');
    const host = document.getElementById('capsule-host');
    if (!host) return;

    const completedCount = state.completedLevels.length;
    const totalStars = Object.values(state.levelStars||{}).reduce((s,v)=>s+v,0);
    const name = state.playerName || 'Патник';
    const completion = Math.floor((completedCount/37)*100);

    host.innerHTML = `
      <div class="text-center mb-6">
        <div class="text-6xl mb-3" style="filter:drop-shadow(0 0 30px rgba(255,215,0,0.6))">🏛️</div>
        <h2 class="text-3xl font-cinzel font-bold gold-shimmer bg-clip-text text-transparent mb-2">Тестамент-Капсула</h2>
        <p class="text-[#FFF8E7]/70 font-caveat text-xl">"Светот е книга, а ти прочита ${completion}% од неа."</p>
      </div>

      <div class="grid grid-cols-3 gap-2 mb-6">
        <div class="bg-yellow-500/10 border border-yellow-500/30 rounded-2xl p-3 text-center">
          <p class="text-2xl font-bold text-yellow-400">${completedCount}</p>
          <p class="text-xs text-[#FFF8E7]/60">Нивоа</p>
        </div>
        <div class="bg-yellow-500/10 border border-yellow-500/30 rounded-2xl p-3 text-center">
          <p class="text-2xl font-bold text-yellow-400">${totalStars}</p>
          <p class="text-xs text-[#FFF8E7]/60">Ѕвезди</p>
        </div>
        <div class="bg-yellow-500/10 border border-yellow-500/30 rounded-2xl p-3 text-center">
          <p class="text-2xl font-bold text-yellow-400">${(state.collectedFacts||[]).length}</p>
          <p class="text-xs text-[#FFF8E7]/60">Свитоци</p>
        </div>
      </div>

      <div class="bg-gradient-to-br from-blue-900/20 to-purple-900/20 border border-yellow-500/30 rounded-2xl p-5 mb-5">
        <p class="text-yellow-400 font-bold mb-2 text-sm flex items-center gap-2">✨ Остави твоја мудрост за идните патници:</p>
        <textarea id="wisdom-input" placeholder="Што научи од Александар? (нпр. 'Знаењето е најголемата круна.')" maxlength="200" rows="2" class="w-full bg-black/40 border border-yellow-500/20 rounded-xl p-3 text-[#FFF8E7] placeholder:text-[#FFF8E7]/30 focus:outline-none focus:border-yellow-500/50 resize-none text-sm"></textarea>
        <div class="flex gap-2 mt-2">
          <button onclick="Legacy.submitWisdom()" class="game-btn flex-1 py-2 text-sm flex items-center justify-center gap-2">
            <i data-lucide="send" class="w-4 h-4"></i> Праќај го во ѕидот (+25 монети)
          </button>
        </div>
      </div>

      <div class="grid grid-cols-2 gap-3">
        <button onclick="Legacy.showPassport()" class="game-btn-sm justify-center py-3 flex items-center gap-2">
          <i data-lucide="badge" class="w-4 h-4"></i> Мојот Пасош
        </button>
        <button onclick="showScreen('wisdomwall');Legacy.renderWisdomWall();" class="game-btn-sm justify-center py-3 flex items-center gap-2">
          <i data-lucide="quote" class="w-4 h-4"></i> Ѕид на Мудрост
        </button>
      </div>
    `;
    if (typeof lucide !== 'undefined') lucide.createIcons();
  },

  // === INIT ===
  init() {
    console.log('[Legacy] Living Legacy Capsule initialized — World\'s first player-generated wisdom system in an educational game.');
    // Ensure passport ID exists
    this.getPassportId();
  }
};

// Auto-init on load
if (typeof window !== 'undefined') {
  window.Legacy = Legacy;
  // Init after DOM ready
  if (document.readyState !== 'loading') Legacy.init();
  else document.addEventListener('DOMContentLoaded', () => Legacy.init());
}
